/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
              "on-secondary-container": "#e1ffec",
              "inverse-on-surface": "#4d556b",
              "on-primary-fixed": "#000000",
              "surface-dim": "#020617",
              "on-surface-variant": "#cbd5e1",
              "on-tertiary-container": "#000000",
              "on-error": "#ffffff",
              "surface-bright": "#1e293b",
              "primary": "#a7a5ff",
              "tertiary-fixed": "#ff9198",
              "surface-tint": "#a7a5ff",
              "error-container": "#a70138",
              "surface": "#020617",
              "on-secondary-fixed-variant": "#006544",
              "on-primary-fixed-variant": "#1a0099",
              "outline-variant": "#334155",
              "primary-container": "#9795ff",
              "secondary-fixed-dim": "#58e7ab",
              "primary-fixed-dim": "#8885ff",
              "error": "#ff6e84",
              "secondary-dim": "#58e7ab",
              "on-secondary": "#005a3c",
              "inverse-primary": "#4e45e4",
              "primary-dim": "#645efb",
              "primary-fixed": "#9795ff",
              "on-surface": "#f8fafc",
              "on-primary": "#1c00a0",
              "outline": "#94a3b8",
              "on-tertiary-fixed": "#39000a",
              "surface-variant": "#0f172a",
              "tertiary-container": "#fc3559",
              "surface-container-high": "#1e293b",
              "tertiary": "#ff6f7d",
              "surface-container-lowest": "#020617",
              "surface-container-low": "#0b1120",
              "secondary-fixed": "#69f6b8",
              "tertiary-dim": "#e21e49",
              "on-secondary-fixed": "#00452d",
              "secondary": "#69f6b8",
              "background": "#020617",
              "error-dim": "#d73357",
              "inverse-surface": "#faf8ff",
              "secondary-container": "#006c49",
              "tertiary-fixed-dim": "#ff7984",
              "on-error-container": "#ffb2b9",
              "surface-container-highest": "#1e293b",
              "on-background": "#f8fafc",
              "on-tertiary": "#49000f",
              "surface-container": "#0f172a",
              "on-tertiary-fixed-variant": "#78001f",
              "on-primary-container": "#14007e"
            },
            fontFamily: {
              "headline": ["Space Grotesk", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"}
        }
    },
    plugins: [],
}
